### ISSUE TITLE
Handle errors gracefully in DAPR dashboard server 0.15.0

### ISSUE THREAD

**Issue by MisterFreeze** [dapr/dashboard#279]
## DAPR dashboard server handles errors gracefully

With an invalid API call do the DAPR dashboard API, the API serving process logs an error messsage, returns a 4XX or 5XX error reflecting the cause of the failure, and keeps its ability to serve requests.

## DAPR dashboard server crashes

With a fresh DAPR install on a kubernetes cluster, and no dapr applications deployed, an attempt to access the dapr-dashboard via kubectl port-forwarding was made. When connecting to the local port with a web browser, the dapr-dashboard process crashes. Full error message below

```bash
Dapr Dashboard running on http://localhost:8080
panic: runtime error: index out of range [0] with length 0

goroutine 45 [running]:
github.com/dapr/dashboard/pkg/instances.(*instances).GetControlPlaneStatus.func1({0x2006bda,0x15})
    /home/runner/work/dashboard/dashboard/pkg/instances/instances.go:464+0x7a6
created by github.com/dapr/dashboard/pkg/instances.(*instances).GetControlPlaneStatus in goroutine 49
    /home/runner/work/dashboard/dashboard/pkg/instances/instances.go:446 +0xba
```

## Steps to Reproduce the Problem

initialize dapr on a kubernetes cluster, with dapr dashboard 0.15.0

```bash
user@host:~/some/path$ dapr init -k
```

connect to the dapr-dashboard via kubectl proxy
```bash
user@host:~/some/path$ kubectl port-forward 'dapr-dashboard-<ID>' 8888:8080 --namespace 'dapr-system'
```

open a web browser and point it to http://localhost:8888

## Release Note

RELEASE NOTE: **FIX** handle errors in control panel status when no dapr apps are deployed

**Comment by MisterFreeze** [comment]
Digging a little bit deeper, it seems not all dapr services' pods were ready (see below), which potentially leads to the ContainerStatuses[0] to not be a valid element. Though this is not the "happy" situation, expectation would be to check an array length before accessing it and not crash the server.

https://github.com/dapr/dashboard/blob/master/pkg/instances/instances.go#L464

```bash
kubectl get pods --namespace dapr-system 
NAME                                     READY   STATUS    RESTARTS       AGE
dapr-dashboard-6d7744b449-2zx9r          1/1     Running   14 (86m ago)   3h38m
dapr-operator-5bb4bbcbc-jvsp4            1/1     Running   0              3h38m
dapr-placement-server-0                  1/1     Running   0              3h38m
dapr-scheduler-server-0                  0/1     Pending   0              3h38m
dapr-sentry-759fffd946-8s9zw             1/1     Running   0              3h38m
dapr-sidecar-injector-74579cbcbb-tp7b5   1/1     Running   0              3h38m
```
